version: '3'

services:
  paper-bot:
    build: .
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    restart: always
    command: ["python", "latest_paper_bot.py", "--webhook-url", "${FEISHU_WEBHOOK_URL}"]